name: Build LibXray XCFramework

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual runs

jobs:
  build-xcframework:
    runs-on: macos-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Clone the Xray-core repository into a subdirectory
    - name: Clone Xray-core repository
      run: |
        git clone --depth=1 https://github.com/XTLS/Xray-core.git ./xray-core

    # Move Xray-core to the expected path
    - name: Move Xray-core to expected path
      run: |
        mv ./xray-core ../Xray-core

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.5

    # Install Go Mobile
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        go install golang.org/x/mobile/cmd/gobind@latest
        gomobile init

    - name: Ensure Go modules are initialized
      run: |
        go mod tidy

    # Build the XCFramework
    - name: Build LibXray.xcframework
      run: |
        gomobile bind -target ios,iossimulator,macos -iosversion 15.0
