name: Build LibXray XCFramework

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual runs

jobs:
  build-xcframework:
    runs-on: macos-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.5

    # Install Go Mobile
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    # Build the XCFramework
    - name: Build LibXray.xcframework
      run: |
        gomobile bind -target ios,iossimulator,macos -iosversion 15.0
